name: Publish

on:
  # TODO: TOBE REMOVED
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Build and test

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Prepare file for publication
        run: |
            ./ci/publish.sh

      - id: Publish
        uses: 'google-github-actions/upload-cloud-storage@v1'
        with:
          path: 'public'
          destination: 'geoparquet'
